### ISSUE TITLE
Similarity based demo

### ISSUE THREAD

**Issue by wentinghome** [yongliang-wu/ExploreCfg#1]
Hi, thanks for the great work! I wonder when the similarity-based demo can be available. looking forward to giving it a try. especially the code for calculating the top similar demos.

Thanks!

**Comment by yongliang-wu** [comment]
Sorry for the delayed response. I will release it this weekend. Stay tuned!

**Comment by yongliang-wu** [comment]
> Hi, thanks for the great work! I wonder when the similarity-based demo can be available. looking forward to giving it a try. especially the code for calculating the top similar demos.
> 
> Thanks!

I have added this part. See [clip-retrieve/retrieve.py](https://github.com/yongliang-wu/ExploreCfg/blob/master/clip-retrieve/retrieve.py) for more details. You can simply run this code via` python retrieve.py` to get the results.
